USE case_study;

-- 1. Display the number of states present in the Location Table

SELECT * FROM Location;

SELECT COUNT(distinct State) AS Number_of_states
FROM Location;


-- 2 How many products are of regular type ?

SELECT * FROM Product;

	SELECT count (Product) as Number_of_regular_type_product
	FROM Product
	where type = 'Regular';

-- 3. how much spending has been done on marketing of product ID 1 ?

	SELECT SUM(Marketing) AS TotalSpending
	FROM FACT
	where ProductId =1;




	-- 4. Find out the total profit generated by Colorado state

	SELECT SUM(f.Profit) as Total FROM fact f
	INNER JOIN Location l
	ON f.Area_Code = l.Area_Code
	WHERE l.state ='Colorado';


-- 5. Display the average inventory for each product ID

	SELECT ProductID, AVG(Inventory) AS AVG_Inventory
	FROM fact
	GROUP BY (ProductID)
	ORDER BY ProductID;
	
	
-- 6. Display the Average budget of the Product where the average budget
-- Margin should be greater than 100 


	SELECT ProductID,AVG(Budget_Sales) AS Avg_Budget_Sales 
	FROM fact
	GROUP BY(ProductId)
	HAVING AVG(Budget_Margin) > 100
	ORDER BY ProductId;



--7. Display the average total expense of each product ID on an individual date.














	SELECT * FROM FACT;
	SELECT * FROM Product;
	SELECT * FROM Location;













